---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: Python app that displays the current date and time.
  annotations:
    github.com/project-slug: laz-rb/python-app

spec:
  type: service
  owner: development
  lifecycle: experimental
